# Generated by Django 4.2.1 on 2023-05-29 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ('name', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('address', models.CharField(blank=True, max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
            },
        ),
        migrations.CreateModel(
            name='WebHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('webhook_type', models.IntegerField(choices=[(0, 'Project'), (1, 'Service')], default=0, verbose_name='Type')),
                ('url', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.IntegerField(default=main.models.next_id, primary_key=True, serialize=False)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('scope', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('in_progress', 'In Progress')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_webhook_sent', models.BooleanField(default=False)),
                ('webhook_type', models.IntegerField(choices=[(0, 'Project'), (1, 'Service')], default=0, verbose_name='Type')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='client', chained_model_field='client', on_delete=django.db.models.deletion.CASCADE, to='main.site')),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
            },
        ),
    ]
