# Generated by Django 4.2.1 on 2023-05-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_lineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('in_progress', 'In Progress')], db_index=True, default='open', max_length=255),
        ),
    ]
