# Generated by Django 4.2.1 on 2023-05-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_workorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='part',
            name='part_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
