# Generated by Django 4.2.1 on 2023-05-30 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_lineitem_cost_lineitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='source',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='part',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.manufacturer'),
        ),
    ]
